services:
  mongodb:
    image: mongo:7
    container_name: promocode-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      MONGO_INITDB_DATABASE: promocode

  clickhouse:
    image: clickhouse/clickhouse-server:24
    container_name: promocode-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "-O", "/dev/null", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  redis:
    image: redis:7-alpine
    container_name: promocode-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  mongodb_data:
  clickhouse_data:
  redis_data:
